README.md, action.yml, scripts/run_lean4checker.sh
Add an input and corresponding step for checking the enviornment with lean4checker.
Note, currently this only works for projects which use toolchain/v4.7.0.
=> feat: add support for lean4checker

README.md, action.yml
Remove `- uses: actions/checkout@v4` from the action and specify in the readme to use the comand in workflows.
Motivation:
1. This matches common practice in actions, eg: 
- [Github Action with TeXLive](https://github.com/marketplace/actions/github-action-with-texlive)
- [GH Release](https://github.com/marketplace/actions/gh-release)
- [Setup Node.js environment](https://github.com/marketplace/actions/setup-node-js-environment)
- [run-ansible-lint](https://github.com/marketplace/actions/run-ansible-lint)
2. This enables the use case when the workflow where `lean-action` is used first checks out a  copy of the repo, then does something else before using `lean-action`.
=> ✨ relocate checkout

.github/dependabot.yml
The actions used by this action are rather stable and so this won't often be required but a useful convenience in the long term to keep all the used actions up to date.
=> :sparkles: Add dependabot to notify when actions are updated

README.md
In anticipation of `lean-action` often being updated, most likely because the underlying lean / lake / etc is updated, recommend all users of the action to take advantage of dependabot. In such a way the repos using the action receive notification when updates happen.
=> :memo:   Update README.md to recommend dependabot

README.md
missing version info causes an error
=> add version info

CHANGELOG.md, README.md, action.yml
Pass a new `build-args` input to `lake build` in the build step.
closes #15
=> feat: add `build-args` input

CHANGELOG.md, README.md, action.yml
Improve the user interface for detecting a Mathlib dependency and running `lake exe cache get`.
Rename `mathlib-cache` -> `get-mathlib-cache`.
Rename default value for `get-mathlib-cache` from empty string -> "auto".
=> fix: rename `mathlib-cache` -> `get-mathlib-cache` and improve interface

action.yml, scripts/detect_mathlib.sh, scripts/install_elan.sh
Add a step to the action which:
- reports if mathlib is used
- reports the lake version
- reports the lean version
resolves #12
=> feat: add a step that logs the version of lake and lean

action.yml, scripts/lake_test.sh, scripts/step_summaries/lake_check_error.md
Check for a test runner before running lake test with `lake check-test`.
Add a step summary when `lake check-test` fails.
=> feat: add `lake check-test` check before running `lake test`

.github/workflows/functional_tests.yml, CHANGELOG.md, README.md, action.yml
`use-github-cache` input specifies if `lean-action` should use `actions/cache`.
`lean-action`'s ci workflows are currently the primary use case for disabling `action/cache`.
=> feat: add `use-github-cache` input

.github/workflows/functional_tests.yml
Moving functional tests to a subdirectory doesn't work correctly. We can use actions instead. 
Reverts leanprover/lean-action#49
=> Revert "refactor: move functional tests to a dedicated directory"

scripts/install_elan.sh
Depending on the usage, elan-init files may remain. For example, when the “commit all changes” action is executed after lean-action.
=> fix: remove `elan-init` file

action.yml
The GitHub cache has caused problems on runs of `lean-action` after updating Lean version.
To fix this and improve the overall caching strategy, add hashes of the `lean-toolchain` and `lake-manifest.json` files to cache keys, narrowing cache hits to runs of `lean-action` with the same toolchain and lake manifest.
=> fix: improve GitHub cache keys

.github/functional_tests/auto_config_false/action.yml, .github/functional_tests/auto_config_true/action.yml, .github/functional_tests/lake_lint_failure/action.yml, .github/functional_tests/lake_lint_success/action.yml, .github/workflows/functional_tests.yml, README.md, action.yml, scripts/config.sh, scripts/lake_lint.sh, scripts/set_output_parameters.sh
The `lint` input functions similarly to the `test` input, allowing the user to run `@[lint_driver]` targets with `lean-action`.
Remove the `lint-module` input as users can now use a lint driver to call the Batteries linting framework.
Closes #46
=> feat: add `lint` input to control the `lake lint` step

.github/functional_tests/auto_config_false/action.yml, .github/functional_tests/auto_config_true/action.yml, .github/functional_tests/lake_check_test_failure/action.yml, .github/functional_tests/lake_init_failure/action.yml, .github/functional_tests/lake_init_success/action.yml, .github/functional_tests/lake_lint_failure/action.yml, .github/functional_tests/lake_lint_success/action.yml, .github/functional_tests/lake_test_failure/action.yml, .github/functional_tests/lake_test_success/action.yml, .github/functional_tests/subdirectory_lake_package/action.yml, .github/workflows/functional_tests.yml, CHANGELOG.md, README.md, scripts/install_elan.sh
Using `elan-init.sh` will make the `install_elan.sh` script easier to maintain and allow lean-action to support additional runners, e.g. macos.
Additionally, update all instances of elan installation in the functional tests to use `elan-init.sh`
Closes #83
=> feat: switch elan installation method from  tar -> `elan-init.sh`

.github/functional_tests/auto_config_false/action.yml, .github/functional_tests/lake_check_test_failure/action.yml, .github/functional_tests/lake_init_failure/action.yml, .github/functional_tests/lake_init_success/action.yml, .github/functional_tests/subdirectory_lake_package/action.yml, CHANGELOG.md, README.md, action.yml
The final `set-output-parameters` step which was set to run `if: always()` was breaking the automatic expansion of the log groups. Remove this step and update the tests to use the default, empty string, value of the outputs to determine if the step wasn't run.
=> fix: remove set-output-parameters step to fix log group expansion

CHANGELOG.md, scripts/lake_build.sh, scripts/lake_lint.sh, scripts/lake_test.sh
Ending the log group when a lake command fails prevented the log group from expanding on a command failure.
Related to #92
=> fix: only end log group if lake command succeeds

CHANGELOG.md, action.yml
Calling `actions/cache` in combination with `actions/cache/save` caused redundant cache saves resulting in post-run error messages. `actions/cache/restore` doesn't result in a post-run cache save.
Closes #96
=> fix: replace `actions/cache` with `actions/cache/restore`

README.md, action.yml
Before this change, GitHub runners with different CPU architecture would share caches (for example, ubuntu-latest and ubuntu-24.04-arm).
This was potentially the cause of #116 
[See also the discussion of if it is possible to share files in `.lake` across different architectures on Zulip](https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/x64.20and.20arm64.20GitHub.20runners.20sharing.20cached.20.60.2Elake.60.20files)
=> fix: update the cache key to include {{ runner.arch }}

.github/functional_tests/reinstall-transient-toolchain/action.yml, .github/workflows/functional_tests.yml, CHANGELOG.md, README.md, action.yml
This PR adds the option to check if the current toolchain is a transient one hosted on the lean4-pr-releases repository. If so, `lean-action` will remove the old version of the toolchain. This ensures a fresh version of the toolchain is always used to run CI.
This is an important step in many Mathlib CI workflows, and adding it to this action would allow us to switch some custom workflows over to run mostly via `lean-action`.
=> feat: reinstall transient `lean4-pr-releases` toolchains

.github/functional_tests/mk_all-check/action.yml, .github/workflows/functional_tests.yml, README.md, action.yml, scripts/mk_all_check.sh
This command checks that all files in the default target's directory are imported in the main file. In repositories such as FLT, this check is run before other build steps, to ensure every relevant file is built, but it must be run after Elan has been initialized. So to use `lean-action` in FLT, we would like to incorporate the mk_all check as a step.
=> feat: option for running lake exe mk_all --check
